

name: CI

on:
  push:
    branches: 
      -develop 
      -main
  pull_request:
    branches: 
      -develop 
      -main


jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v2
        with: 
           node-version: 14.x 
      - name: Install dependencies
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm run test